before:
  hooks:
    - go mod vendor
builds:
  - main: ./cmd/rpi-violet/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w
      - -X github.com/gaiaz-iusipov/rpi-violet/pkg/version.version={{.Version}}
      - -X github.com/gaiaz-iusipov/rpi-violet/pkg/version.commit={{.ShortCommit}}
      - -X github.com/gaiaz-iusipov/rpi-violet/pkg/version.date={{time "2006-01-02"}}
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
nfpms:
  - id: nfpms
    homepage: "https://github.com/gaiaz-iusipov/rpi-violet"
    maintainer: Gaiaz Iusipov <g.iusipov@gmail.com>
    description: PRI Violet.
    license: MIT
    formats:
      - deb
    dependencies:
      - libraspberrypi-bin
    bindir: /usr/bin
    contents:
      - src: "scripts/lib/systemd/system/**"
        dst: "/lib/systemd/system"
      - src: "config.dist.toml"
        dst: "/etc/rpi-violet.toml"
        type: config
