debugPort = 6060
timeZone = "Europe/Moscow"

[sentry]
# dns = ""
timeout = "2s"

[gpio]
# lightPin = ""

[telegram]
# botToken = ""
# chatId = 0
clientTimeout = "10s"

[raspistill]
quality = 85
timeout = "10s"

[[cron.jobs]]
spec = "0 7 * * *"
withLightSwitch = true
lightState = true
withPhoto = true

[[cron.jobs]]
spec = "0 22 * * *"
withLightSwitch = true
lightState = false
withPhoto = false

[[cron.jobs]]
spec = "@daily"
withLightSwitch = false
withPhoto = true
